package main

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"os"

	// 1. Import the pure Go driver instead of mattn/go-sqlite3
	_ "modernc.org/sqlite"
)

// --- Structs matching the JSON Schema ---

type AutoGeneratedJSON struct {
	ProtoReaderBundles []ProtoReaderBundle `json:"ProtoReaderBundles"`
}

type ProtoReaderBundle struct {
	ID              int         `json:"Id"`
	ReaderID        string      `json:"reader_id"`
	SiteID          string      `json:"site_id"`
	SentTimestampMs int64       `json:"sent_timestamp_ms"`
	ProtoReads      []ProtoRead `json:"ProtoReads"`
}

type ProtoRead struct {
	ID                  int     `json:"Id"`
	ProtoReaderBundleID int     `json:"ProtoReaderBundleId"`
	TimestampNs         int64   `json:"timestamp_ns"`
	Confidence          float64 `json:"confidence"`
	AntennaID           string  `json:"antenna_id"`
	AntennaType         string  `json:"antenna_type"`
	X                   float64 `json:"x"`
	Y                   float64 `json:"y"`
	ItemID              string  `json:"item_id"`
	FloorID             string  `json:"floor_id"`
}

func main() {
	// 1. Initialize Log File
	logFile, err := os.OpenFile("app.log", os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0666)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to open log file: %v\n", err)
		os.Exit(1)
	}
	defer logFile.Close()

	mw := io.MultiWriter(os.Stdout, logFile)
	log.SetOutput(mw)
	log.SetFlags(log.Ldate | log.Ltime | log.Lshortfile)

	log.Println("--- Starting Go JSON-to-SQLite Import Process ---")

	// 2. Read JSON file
	fileBytes, err := os.ReadFile("data.json")
	if err != nil {
		log.Fatalf("ERROR: Failed to read JSON file: %v\n", err)
	}

	// 3. Parse JSON
	var data AutoGeneratedJSON
	if err := json.Unmarshal(fileBytes, &data); err != nil {
		log.Fatalf("ERROR: Failed to parse JSON: %v\n", err)
	}
	log.Printf("INFO: Loaded %d ProtoReaderBundles from JSON.\n", len(data.ProtoReaderBundles))

	// 4. Connect to SQLite
	// Note: We change the driver name from "sqlite3" to "sqlite"
	db, err := sql.Open("sqlite", "./reader_data.db")
	if err != nil {
		log.Fatalf("ERROR: Failed to connect to database: %v\n", err)
	}
	defer db.Close()

	// 5. Create Tables with Foreign Key constraints enabled
	if _, err := db.Exec("PRAGMA foreign_keys = ON;"); err != nil {
		log.Fatalf("ERROR: Failed to enable foreign keys: %v\n", err)
	}

	createTablesSQL := `
	CREATE TABLE IF NOT EXISTS proto_reader_bundles (
		id INTEGER PRIMARY KEY,
		reader_id TEXT NOT NULL,
		site_id TEXT NOT NULL,
		sent_timestamp_ms INTEGER NOT NULL
	);

	CREATE TABLE IF NOT EXISTS proto_reads (
		id INTEGER PRIMARY KEY,
		proto_reader_bundle_id INTEGER NOT NULL,
		timestamp_ns INTEGER NOT NULL,
		confidence REAL NOT NULL,
		antenna_id TEXT NOT NULL,
		antenna_type TEXT NOT NULL,
		x REAL NOT NULL,
		y REAL NOT NULL,
		item_id TEXT NOT NULL,
		floor_id TEXT NOT NULL,
		FOREIGN KEY (proto_reader_bundle_id) REFERENCES proto_reader_bundles(id) ON DELETE CASCADE
	);`

	if _, err := db.Exec(createTablesSQL); err != nil {
		log.Fatalf("ERROR: Failed to create tables: %v\n", err)
	}
	log.Println("INFO: Database schema established.")

	// 6. Begin a database transaction
	tx, err := db.Begin()
	if err != nil {
		log.Fatalf("ERROR: Failed to start transaction: %v\n", err)
	}

	// Prepare statements inside the transaction
	insertBundleStmt, err := tx.Prepare(`
		INSERT INTO proto_reader_bundles (id, reader_id, site_id, sent_timestamp_ms) 
		VALUES (?, ?, ?, ?)
		ON CONFLICT(id) DO UPDATE SET 
			reader_id=excluded.reader_id, 
			site_id=excluded.site_id, 
			sent_timestamp_ms=excluded.sent_timestamp_ms;
	`)
	if err != nil {
		tx.Rollback()
		log.Fatalf("ERROR: Failed to prepare bundle statement: %v\n", err)
	}
	defer insertBundleStmt.Close()

	insertReadStmt, err := tx.Prepare(`
		INSERT INTO proto_reads (id, proto_reader_bundle_id, timestamp_ns, confidence, antenna_id, antenna_type, x, y, item_id, floor_id) 
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
		ON CONFLICT(id) DO UPDATE SET 
			proto_reader_bundle_id=excluded.proto_reader_bundle_id,
			timestamp_ns=excluded.timestamp_ns,
			confidence=excluded.confidence,
			antenna_id=excluded.antenna_id,
			antenna_type=excluded.antenna_type,
			x=excluded.x,
			y=excluded.y,
			item_id=excluded.item_id,
			floor_id=excluded.floor_id;
	`)
	if err != nil {
		tx.Rollback()
		log.Fatalf("ERROR: Failed to prepare read statement: %v\n", err)
	}
	defer insertReadStmt.Close()

	// 7. Loop and Insert nested data
	for _, bundle := range data.ProtoReaderBundles {
		_, err := insertBundleStmt.Exec(bundle.ID, bundle.ReaderID, bundle.SiteID, bundle.SentTimestampMs)
		if err != nil {
			tx.Rollback()
			log.Fatalf("ERROR: Failed to insert bundle %d: %v\n", bundle.ID, err)
		}
		log.Printf("INFO: Inserting Bundle ID: %d...\n", bundle.ID)

		for _, read := range bundle.ProtoReads {
			_, err := insertReadStmt.Exec(
				read.ID,
				bundle.ID,
				read.TimestampNs,
				read.Confidence,
				read.AntennaID,
				read.AntennaType,
				read.X,
				read.Y,
				read.ItemID,
				read.FloorID,
			)
			if err != nil {
				tx.Rollback()
				log.Fatalf("ERROR: Failed to insert read %d (bundle %d): %v\n", read.ID, bundle.ID, err)
			}
			log.Printf("INFO:   -> Stored Read ID: %d for Bundle ID: %d\n", read.ID, bundle.ID)
		}
	}

	// Commit transaction
	if err := tx.Commit(); err != nil {
		log.Fatalf("ERROR: Failed to commit transaction: %v\n", err)
	}

	log.Println("SUCCESS: All relational data has been cleanly written to SQLite.")
}
